spring:
  application:
    name: Good Feel Tour System
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  # H2 Console Configuration (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Thymeleaf Configuration
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      add-mappings: true
      static-locations:
        - classpath:/static/
      cache:
        cachecontrol:
          max-age: 0
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# Server Configuration
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

# Logging Configuration
logging:
  level:
    com.gftour: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# JWT Configuration
jwt:
  secret: gftour-secret-key-for-development-only-change-in-production
  expiration: 86400000  # 24 hours
  refresh-expiration: 604800000  # 7 days