server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: gftour
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/gftour?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    
  # Security 설정
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# 로깅 설정
logging:
  level:
    com.gftour: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 페이징 기본 설정
spring.data.web.pageable:
  default-page-size: 20
  max-page-size: 100